### PR TITLE
add some strings, UK

### PR DESCRIPTION
**Pull request by perdolka**

### CODE REVIEW

**Comment by Lej77** [comment]
@perdolka Thanks! Are these pull requests done?

**Comment by perdolka** [comment]
<a href="http://piccy.info/view3/12371500/6609a8ea8f30b5677efc3d9b21729b21/1200/" target="_blank">Piccy.info - Free Image Hosting</a><a href="http://i.piccy.info/a3c/2018-05-29-20-04/i9-12371500/800x144-r" target="_blank"></a>

Here should be "Введення" - UK," Ввод" - RU

**Comment by Lej77** [comment]
Well that is the `options_Commands_Info` message.

**Comment by Lej77** [comment]
I have updated the extension to version 5.7 and included the locale changes in the new version.

**Pull request merged**
